version: '3.8'

services:
  # Local Prometheus server for testing purposes
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Local Pushgateway server for testing purposes
  pushgateway:
    image: prom/pushgateway:latest

    ports:
      - "9091:9091"